### ISSUE TITLE
Support IntelliJ / Jetbrains Products

### ISSUE THREAD

**Issue by JonasGroeger** [zxqfl/TabNine#13]
A lot of users = profit

**Comment by croogie** [comment]
Are there any plans to support JetBrains' IDEs?

**Comment by zxqfl** [comment]
Yes, it is planned.

**Comment by alexandervantrijffel** [comment]
It would be awesome if [Jetbrains Rider](https://www.jetbrains.com/rider) is also supported by your amazing autocompleter.

**Comment by pjvds** [comment]
@zxqfl I would love to see it as well, especially Rider, Goland and IntelliJ (shouldn't be hard to support the entire Jetbrains family)

ps: thanks for the great autocompleter, I'm really enjoying TabNine

**Comment by cihantas** [comment]
Any updates on this?

**Comment by liuxinsi** [comment]
Any updates on this?

**Comment by viktorvillalobos** [comment]
We are waiting!

**Comment by zxqfl** [comment]
We're working on it! You can sign up at https://tabnine.com/install (click 'other') to be notified when it's released.

**Comment by pjvds** [comment]
> We're working on it! You can sign up at https://tabnine.com/install (click 'other') to be notified when it's released.

Awesome news @zxqfl! ❤️

**Comment by smashmirrorcardboardface** [comment]
why closed?

**Comment by quantumpacket** [comment]
@smashmirrorcardboardface it's not closed. You may be referring to dupe #91.

**Comment by smashmirrorcardboardface** [comment]
apologies, yes

**Comment by danherrera** [comment]
Just bought a license! Super excited for IntelliJ support! 

Keep up the great work! 🌞

**Comment by SimonZhao777** [comment]
Please support IntelliJ IDE, I have already signed up and we are really looking forward to try this amazing tool on our favorite IDE.

**Comment by yuerolling** [comment]
A  new Idea is exciting when it is coming

**Comment by bnyboy** [comment]
Yes! IntelliJ support please!

**Comment by gpetrosyan** [comment]
Please support IntelliJ!

**Comment by rckoepke** [comment]
https://plugins.jetbrains.com/plugin/10209-lsp-support

This may help, as TabNine apparently interfaces via LSP.

**Comment by zxqfl** [comment]
I've created an IntelliJ plugin which is now pending approval by JetBrains. If you'd like to help test it, you can install the plugin manually from https://update.tabnine.com/intellij/TabNine-0.0.1.jar. You can find instructions for installing manually [here](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).

If you encounter any issues, please write to me at jacob@tabnine.com.

**Comment by alexlioralexli** [comment]
Any plans for PyCharm integration?

**Comment by zxqfl** [comment]
The plugin should work for all the JetBrains IDEs, including PyCharm.

**Comment by alexshenia** [comment]
@zxqfl Nope, I can't install this plugin on RubyMine

**Comment by alexshenia** [comment]
@zxqfl 
<img width="399" alt="Screen Shot 2019-07-31 at 3 05 00 AM" src="https://user-images.githubusercontent.com/5398316/62173806-084c2e80-b340-11e9-8f9c-1975f1948de3.png">

**Comment by zxqfl** [comment]
I'll look into it

**Comment by alexshenia** [comment]
@zxqfl tested on ruby mine 2019.1.3 and 2019.2

**Comment by filthysocks** [comment]
I get "Plugin 'TabNine' is incompatible with this installation" as well for pycharm 2018.3.3 and 2019.2 on ubuntu 18.04

**Comment by manudss** [comment]
Same for me, not working for last version  of IntelliJ IDEA 2019.2 (build UI-192.5728.98)

**Comment by zgqq** [comment]
Same for me, not working for last version of IntelliJ IDEA 2019.2

**Comment by guoguoguilai** [comment]
Same for me, not working for last version of Pycharm 2018.2

**Comment by chadkouse** [comment]
I took the jar - renamed it to .zip -- unzipped it.. and then edited `META-INF/plugin.xml`

The line to change is:
```diff
<change-notes>
      Add change notes here.&lt;br&gt;
      &lt;em&gt;most HTML tags may be used&lt;/em&gt;</change-notes>
-  <idea-version since-build="182.4892" until-build="182.*"/>
+  <idea-version since-build="182.4892" until-build="192.*"/>
  <id>com.tabnine.TabNine</id>
  <name>TabNine</name>
```
Then zip it back up, rename it back to .jar -- and install it.  It threw an error for me when I first started it about a Text File being busy -- but it's working nonetheless!

**Comment by zxqfl** [comment]
Thanks @chadkouse! I found the issue: I needed to set [updateSinceUntilBuild](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/README.md) to `false`.

Here is the fixed plugin: https://update.tabnine.com/intellij/TabNine-0.0.2.jar (tested in IDEA and PhpStorm)

**Comment by rckoepke** [comment]
Trying this with fresh Ubuntu/PyCharm 2019.2 install, I get
`tabnine was unable to install the python semantic completion backend.The command that failed was _pip install python-language-server_`

But when I run that command from PyCharm terminal, the installation of python-language-server goes smoothly with no errors. No option that I can find to re-initiate installation script.

**Comment by zxqfl** [comment]
@rckoepke You could try giving an absolute path to the python language server, but I would actually recommend disabling it with TabNine::no_sem since PyCharm's built-in Python completion is probably better than python-language-server.

**Comment by rckoepke** [comment]
Thank you! didn't realize exactly what that was doing. Enabled with Deep TabNine beta, and it seems to be working wonderfully. Thank you. Great work all around.

**Comment by michalpokojski** [comment]
Webstorm 2019.2 works well, but something went wrong with predictions list width :D
![image](https://user-images.githubusercontent.com/29205657/62304100-9da10d00-b47d-11e9-8d22-3c78748bc5c6.png)

**Comment by rckoepke** [comment]
@michalpokojski - type `tabnine::no_sem` into either the IDE editor or IDE python console to fix that. It's long because of an error message about the semantic server. Turning that off removes the super long error message.

**Comment by michalpokojski** [comment]
thank you @rckoepke I've acknowledged the same issue as you tho. Completions seems not to be sorted by relevance. 
![image](https://user-images.githubusercontent.com/29205657/62324512-01412f80-b4aa-11e9-8ef3-9f1181ea2fed.png)

**Comment by sergeiruzkiicode** [comment]
yes, I had a problem with for x in self: - no chance to keep self: after enter

**Comment by nzlov** [comment]
@zxqfl not working for last version of Goland 2019.2
```
java.lang.Throwable: Can't get completions because TabNine process is not started yet.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at TabNineCompletionContributor.getProcOrPrintError(TabNineCompletionContributor.java:144)
	at TabNineCompletionContributor.lambda$retrieveCompletions$1(TabNineCompletionContributor.java:153)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$null$1(ApplicationUtil.java:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by recolic** [comment]
It's working on IDEA 2019.2, but there's an error.

```java
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:196)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:113)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:170)
	at TabNineCompletionContributor.retrieveCompletions(TabNineCompletionContributor.java:172)
	at TabNineCompletionContributor.fillCompletionVariants(TabNineCompletionContributor.java:194)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:161)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:120)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:60)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:828)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:277)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:130)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:121)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:102)
	at com.intellij.openapi.application.ex.ApplicationUtil.runWithCheckCanceled(ApplicationUtil.java:82)
	at com.intellij.openapi.application.ex.ApplicationUtil.runWithCheckCanceled(ApplicationUtil.java:66)
	at TabNineCompletionContributor.retrieveCompletions(TabNineCompletionContributor.java:152)
	... 29 more
```

**Comment by zbluex** [comment]
It's working on Clion 2019.2, but it reports an error
java.lang.Throwable: Exception communicating with TabNine: java.io.IOException: Stream closed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at TabNineProcess.communicateLine(TabNineProcess.java:75)
	at TabNineProcess.request(TabNineProcess.java:49)
	at TabNineCompletionContributor.lambda$retrieveCompletions$1(TabNineCompletionContributor.java:169)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$null$1(ApplicationUtil.java:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by imzion** [comment]
> Webstorm 2019.2运行良好，但预测列表宽度出现问题：D 作为插件关闭时的参考：
> ![图片](https://user-images.githubusercontent.com/29205657/62304100-9da10d00-b47d-11e9-8d22-3c78748bc5c6.png)
How can I trigger a reminder?

**Comment by Aloxaf** [comment]
@zxqfl  It crashed on Clion 2019.2

<details>
  <summary>Backtrace</summary>

```
java.lang.Throwable: Can't get completions because TabNine process is not started yet.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at TabNineCompletionContributor.getProcOrPrintError(TabNineCompletionContributor.java:144)
	at TabNineCompletionContributor.lambda$retrieveCompletions$1(TabNineCompletionContributor.java:153)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$null$1(ApplicationUtil.java:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details>
<summary>System Information</summary>

- OS: Arch Linux
- jdk: JBRSDK11

</details>

**Comment by michiomochi** [comment]
@zxqfl 
Thanks great plugin!
It reports an error when working on intellij 2019.2

stacktrace.txt
```
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:196)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:101)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:170)
	at TabNineCompletionContributor.retrieveCompletions(TabNineCompletionContributor.java:172)
	at TabNineCompletionContributor.fillCompletionVariants(TabNineCompletionContributor.java:194)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:135)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:126)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:100)
	at com.intellij.openapi.application.ex.ApplicationUtil.runWithCheckCanceled(ApplicationUtil.java:65)
	at com.intellij.openapi.application.ex.ApplicationUtil.runWithCheckCanceled(ApplicationUtil.java:48)
	at TabNineCompletionContributor.retrieveCompletions(TabNineCompletionContributor.java:152)
	... 29 more
```

induced.txt
```
Following exceptions happened soon after this one, most probably they are induced.


2019-08-08T13:09:55.500
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:196)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:101)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:170)
	at TabNineCompletionContributor.retrieveCompletions(TabNineCompletionContributor.java:172)
	at TabNineCompletionContributor.fillCompletionVariants(TabNineCompletionContributor.java:194)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:135)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:126)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:100)
	at com.intellij.openapi.application.ex.ApplicationUtil.runWithCheckCanceled(ApplicationUtil.java:65)
	at com.intellij.openapi.application.ex.ApplicationUtil.runWithCheckCanceled(ApplicationUtil.java:48)
	at TabNineCompletionContributor.retrieveCompletions(TabNineCompletionContributor.java:152)
	... 29 more
```

**Comment by Spodnet** [comment]
Using 0.1.2, this has popped up, not sure what triggered it but it appeared whilst I was working

```
java.lang.AssertionError: The new element doesn't match the prefix
	at com.intellij.codeInsight.completion.CompletionResult.withLookupElement(CompletionResult.java:59)
	at com.intellij.codeInsight.completion.XmlCompletionContributor$3.lambda$addCompletions$0(XmlCompletionContributor.java:131)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:161)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:56)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.addElement(CompletionServiceImpl.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.addAllElements(CompletionResultSet.java:86)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.lambda$addAllElements$0(CompletionServiceImpl.java:134)
	at com.intellij.codeInsight.completion.CompletionThreadingBase.withBatchUpdate(CompletionThreadingBase.java:33)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.addAllElements(CompletionServiceImpl.java:134)
	at TabNineCompletionContributor.fillCompletionVariants(TabNineCompletionContributor.java:219)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.completion.XmlCompletionContributor$3.addCompletions(XmlCompletionContributor.java:126)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.XmlCompletionContributor.fillCompletionVariants(XmlCompletionContributor.java:181)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by chaotianjiao** [comment]
I have successfully installed 0.1.2 in my pycharm through plugins and restart my IDE, but I found it did not wrok just like the picture shows?
![image](https://user-images.githubusercontent.com/42534375/63310691-3e247780-c32e-11e9-8430-f3e0083f45ca.png)

**Comment by chaotianjiao** [comment]
I have successfully installed 0.1.2 in my pycharm through plugins and restart my IDE, but I found it did not wrok just like the picture shows?

[image](https://user-images.githubusercontent.com/42534375/63310773-9196c580-c32e-11e9-82d2-bf8ab3cd2cc2.png)
upload picture failed......Acturally I did not get the probability，the autocompleter has been done by IDE, not TabNine.
Can any one help me ?
Best wishes!

**Comment by imzion** [comment]
Me too, java and python don't prompt.

**Comment by zxqfl** [comment]
Have you set up your API key by signing up at https://tabnine.com/beta_signup?

**Comment by imzion** [comment]
I am trying!

**Comment by imzion** [comment]
> 您是否通过注册[https://tabnine.com/beta_signup来](https://tabnine.com/beta_signup)设置API密钥？

Does this prove that TabNine is working?

**Comment by imzion** [comment]
![TIM截图20190820100120](https://user-images.githubusercontent.com/35715627/63311752-bb052080-c331-11e9-85e0-0242a51d4213.png)

**Comment by chaotianjiao** [comment]
![image](https://user-images.githubusercontent.com/42534375/63311821-f9024480-c331-11e9-9918-d7948224ee22.png)
oh~ It's my netwrok problem?~

**Comment by chaotianjiao** [comment]
@zxqfl  Thank you !    It works well!
![image](https://user-images.githubusercontent.com/42534375/63312883-65cb0e00-c335-11e9-9a42-c3a2fe11e60b.png)

**Comment by zxqfl** [comment]
Thanks everyone for your feedback. I've created a repository for the IntelliJ plugin to manage any issues: https://github.com/zxqfl/tabnine-intellij
