### ISSUE TITLE
TabNine results yield duplicate letters

### ISSUE THREAD

**Issue by jaydorsey** [zxqfl/TabNine#45]
I'm using TabNine latest, nvim latest, with the deoplete plugin. macOS latest as well. I have semantic completion enabled with solargraph (also latest) as the backend (stdio). My TabNine.toml, .solargraph.yml, and .vimrc files are located here: https://github.com/jaydorsey/dotfiles

I see an issue where the TabNine results show an extra/duplicate letter as in the screenshot below:

![image](https://user-images.githubusercontent.com/191564/50925896-a8348000-1421-11e9-949b-7202869c9436.png)

If I press enter/return it enters the text as present (with the extra character). 

Stopping & restarting nvim makes the problem go away, but not for very long.

I don't remember it doing this when I first enabled semantic completion, but I might be mistaken. It seems to have manifested over the last update or two. I've seen it happen with one other user but they have nearly the same setup I have.

Things I've tried that didn't work:

- Changing the `num_server_instances` (1 - 4) in TabNine.toml
- Changing the `synchronous_timeout_ms` (100-500) in TabNine.toml
- Updating/clearing/downloading the solargraph-cores
- Deleting my TabNine.toml file (in hopes that semantic completion would be disabled)
- Trying a nearly empty vimrc file (also ran PlugClean & restarted nvim after emptying) (below)
- Trying a nearly empty vimrc, and an empty TabNine.toml file

My mostly empty vimrc file:

```
set nocompatible  " We don't want vi compatibility.
set termguicolors " Enable true color support
set t_Co=256

let g:python3_host_prog = '/usr/local/bin/python3'
let g:python_host_prog = '/usr/local/bin/python'

call plug#begin()

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'tbodt/deoplete-tabnine', { 'do': './install.sh' }
let g:deoplete#enable_at_startup = 1
let g:deoplete#ignore_sources = get(g:,'deoplete#ignore_sources',{})
" Disable tags file as a source
let g:deoplete#ignore_sources.ruby = ['tag']

" Use <tab> key to step into the selections
inoremap <expr><tab>  pumvisible() ? "\<c-n>" : "\<tab>"
call plug#end()
```

This does appear to affect things like trying to type `TabNine::restart`, even when I don't select `rrestart` as an autocompletion (I can't call restart by typing)

Other things:

- I can open up a new nvim instance, aside from one that's been impacted by this, and everything works fine
- Restarting nvim completely makes the issue go away for a short period of time (minutes)
- I would try disabling semantic completion, but I don't see a `TabNine::disable_sem` command?

My next step is to try to revert back to an older version of TabNine to see if I could isolate it vs solargraph but I wanted to see if anyone else was having similiar issues or could recommend a setting I haven't looked at.

**Comment by jaydorsey** [comment]
One other thing I noticed that may be relevant:

- When I type one character, everything is OK
- When I type the 2nd character, I get the double-up (always, once it happens the first time)

This happens almost always within 2-3 minutes of starting vim, with TabNine enabled. This makes it impossible to use because I spend more time moving around deleting text than the time it saves me with autocomplete

![tabnine](https://user-images.githubusercontent.com/191564/50930295-a40e5f80-142d-11e9-8aca-8617b43b60cf.gif)

This screenshot is with all my plugins, but the behavior was the same with the lightweight vimrc file I posted earlier.

Thanks for the info @Shougo. Knowing I'm not the only one should (hopefully) help me narrow down the root cause. I may try the tabnine.vim plugin and see if it occurs there too.

**Comment by jaydorsey** [comment]
@shougo, I noticed this error immediately before the duplication occurred most recently.

```
[deoplete] Traceback (most recent call last):
  File "/Users/jay/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 179, in _gather_results
    result = self._get_result(context, source)
  File "/Users/jay/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 195, in _get_result
    charpos = source.get_complete_position(ctx)
  File "/Users/jay/.config/nvim/plugged/deoplete-tabnine/rplugin/python3/deoplete/sources/tabnine.py", line 62, in get_complete_position
    self._response = self._get_response(context)
  File "/Users/jay/.config/nvim/plugged/deoplete-tabnine/rplugin/python3/deoplete/sources/tabnine.py", line 110, in _get_response
    max_num_results=10,
  File "/Users/jay/.config/nvim/plugged/deoplete-tabnine/rplugin/python3/deoplete/sources/tabnine.py", line 124, in _request
    return json.loads(proc.stdout.readline().decode('utf8'))
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error from tabnine: JSONDecodeError('Expecting value: line 1 column 1 (char 0)').  Use :messages / see above for error details.
```

I'm not sure exactly what I did right before that; I was just writing code.

**Comment by jaydorsey** [comment]
I captured a log here: https://gist.github.com/jaydorsey/ad79704a05d9b3fe29b82bbd874e08be

I'm also able to reproduce this issue reliably now, in at least one scenario. I tried to capture the key commands in the gif below:

![screencast 2019-01-10 10-40-49](https://user-images.githubusercontent.com/191564/50979973-aa501a80-14c5-11e9-8529-e099d55a9536.gif)

Basically:

- Move to top of a file in existing project (this probably doesn't matter)
- INSERT mode
- Type a character, wait for autocomplete
- Press SPACE
- Press BACKSPACE
- Press another character

I sometimes have to backspace/type new character a couple times to trigger it

**Comment by jaydorsey** [comment]
Maybe unrelated, but `TabNine::Version` reports 1.10.0, while my `tabnine_config.json` file is below:

```
{"version":"1.0.9","hide_promotional_message":false,"beta_enabled":"No","ignore_all_lsp":false,"semantic_status":{"toml":"Enabled","unknown":"Enabled","ruby":"Enabled"},"disable_auto_update":false}
```

**Comment by jaydorsey** [comment]
More info on the behavior. I don't know if this would help identify the root cause or not but:

After the issue triggers, when I type a single letter, it reads the previous match (my cursor is after the `p` below, but it's suggesting stuff based on the `With`)

![image](https://user-images.githubusercontent.com/191564/50983200-f488ca00-14cc-11e9-9b14-b8868d6f6f51.png)

Typing a second character shows me the doubling:

![image](https://user-images.githubusercontent.com/191564/50983237-108c6b80-14cd-11e9-8a4a-92aee1e47493.png)

Deleting a character skips the doubling again (replaced `p` with `f` but only to show more relevant choices:

![image](https://user-images.githubusercontent.com/191564/50983319-3fa2dd00-14cd-11e9-9f46-1ec0922093e5.png)

I've noticed sometimes though, with some words, it's fine. Until i backspace and re-type and then it's all messed up again.

**Comment by zxqfl** [comment]
Here's what I think is happening: TabNine is printing an extra line in its output, causing the `readline` call at https://github.com/tbodt/deoplete-tabnine/blob/d4d0bccf019b96ea9255eb1ef90ca97907fa2820/rplugin/python3/deoplete/sources/tabnine.py#L123 to read that extra line instead of the correct reponse. (This causes the JSONDecodeError.) After that point, each `readline` call gets TabNine's response to the _previous_ query, leading to the letter doubling effect.

I think TabNine is printing something to stderr. In the most recent version I added some code which logs errors to stderr. This would also explain why I haven't experienced the issue with Sublime, because tabnine-sublime redirects stderr to devnull (https://github.com/zxqfl/tabnine-sublime/blob/45fb2ea0671c34a9960f3370f14f897de4148d56/TabNine.py#L92) whilie deoplete-tabnine redirects it to stdout (https://github.com/tbodt/deoplete-tabnine/blob/d4d0bccf019b96ea9255eb1ef90ca97907fa2820/rplugin/python3/deoplete/sources/tabnine.py#L139).

In the next version I will change TabNine to avoid printing to stderr. In the meantime, you could try changing your deoplete-tabnine to redirect stderr to devnull and see if that fixes the issue.

**Comment by jaydorsey** [comment]
Thanks @zxqfl, I just deleted L139 locally to test it (to let the default go to wherever it should go). That seems to have resolved the issue. I'll keep an eye on it, and try a redirect to /dev/null if I see it pop up again. 🤞

**Comment by Shougo** [comment]
Thank you!
I will fix deoplete-tabnine later.
Please wait.

**Comment by Shougo** [comment]
@zxqfl I think tabnine should include error lines in responce instead of stderr.

**Comment by Shougo** [comment]
I have fixed it in https://github.com/tbodt/deoplete-tabnine/pull/17.

**Comment by Shougo** [comment]
The PR is merged.  So the problem is gone in deoplete-tabnine.
